[build-system]
requires = ["flit_core >=3.5,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pte-stats"
description = "An open-source software package for statistics with time series."
readme = { file = "README.md", content-type = "test/markdown"}
requires-python = ">=3.9"
license = {file = "LICENSE.txt"}
keywords = ["statistics", "timeseries", "eeg", "ieeg"]
authors = [
  {name = "Richard Koehler"}
]
maintainers = [
  {name = "Richard Koehler"}
]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Topic :: Software Development :: Libraries :: Python Modules"
]
dynamic = ["version"]

dependencies = [
  "joblib",
  "numba",
  "numpy",
  "pip",
  "scikit-image",
  "statsmodels"
]

[tool.flit.module]
name = "pte_stats"

[project.optional-dependencies]
test = [
  "pylint",
  "pytest",
]
style = [
  "black",
  "isort"
]

[project.urls]
repository = "https://github.com/richardkoehler/pte-stats"
changelog = "https://github.com/richardkoehler/pte-stats/blob/main/doc/CHANGELOG.md"
bugtracker = "https://github.com/richardkoehler/pte-stats/issues"

[tool.black]
line-length = 79
target-version = ['py310']
exclude = '''
/(
    \.git
  | \.tox
  | .gitignore
  | environment.yml
  | environment_dev.yml
  | LICENSE.txt
  | pylintrc
  | README.md
  | setup.cfg
)/
'''

[tool.isort]
profile = "black"
line_length = 79
py_version = 310
src_paths = ["pte_stats"]
