[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.5,<4"]

[project]
authors = [
  {name = "Richard Koehler"},
]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
description = "An open-source software package for statistics with time series."
dynamic = ["version"]
keywords = ["statistics", "timeseries", "eeg", "ieeg"]
license = {file = "LICENSE.txt"}
maintainers = [
  {name = "Richard Koehler"},
]
name = "pte-stats"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.9"

dependencies = [
  "joblib",
  "numba",
  "numpy",
  "pip",
  "scikit-image",
  "statsmodels",
]

[project.optional-dependencies]
deploy = [
  "flit",
]
dev = [
  "black",
  "isort",
  "mypy",
  "pylint",
  "pytest",
  "pytest-cov",
]

[tool.flit.module]
name = "pte_stats"

[project.urls]
bugtracker = "https://github.com/richardkoehler/pte-stats/issues"
changelog = "https://github.com/richardkoehler/pte-stats/blob/main/doc/CHANGELOG.md"
repository = "https://github.com/richardkoehler/pte-stats"

[tool.black]
exclude = '''
/(
  __pycache__
)/
'''
include = '''
(
    /tests
  | src/pte_stats/
)
'''
line-length = 79
target-version = ['py310']

[tool.isort]
line_length = 79
profile = "black"
py_version = 310
src_paths = ["pte_stats"]

[tool.mypy]
python_version = "3.10"

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = [
  "numba",
  "skimage",
  "statsmodels.stats.multitest",
]
